version: '3.8'

services:
  mariadb:
    image: docker.io/library/mariadb:11.2
    container_name: url_shortener_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: url_shortener_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z

  redis:
    image: docker.io/library/redis:7.2-alpine
    container_name: url_shortener_redis
    restart: always
    command: redis-server --requirepass redis_password --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data:Z